name: Test

on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  repo-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install uv
        run: pipx install uv
      - uses: extractions/setup-just@v2
      - name: Install cbfmt
        run: |
            mkdir /tmp/cbfmt && cd $_
            curl -fsSL -o cbfmt.tar.gz "https://github.com/lukas-reineke/cbfmt/releases/download/v0.2.0/cbfmt_linux-x86_64_v0.2.0.tar.gz"
            tar --strip-components 1 -xvf cbfmt.tar.gz
            mv cbfmt /usr/local/bin/
      - name: Prep venv
        shell: bash
        run: |
          uv venv -p 3.12 venv
          . venv/bin/activate
          uv pip sync --strict requirements/dev.txt
      - name: Check pre-commit hooks
        shell: bash
        run: |
          . venv/bin/activate
          just lint-pc
      - name: Run lints
        shell: bash
        run: |
          . venv/bin/activate
          just lint
      - name: Run documentation tests
        shell: bash
        run: |
          . venv/bin/activate
          just test-doc
  test:
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install uv
      run: pipx install uv
    - uses: extractions/setup-just@v2
    - name: Prep build venv
      shell: bash
      run: |
        uv venv -p ${{ matrix.python-version }} venv/
        . venv/bin/activate
        uv pip sync --strict requirements/dev.txt
    - name: Run Python tests
      shell: bash
      run: |
        . venv/bin/activate
        just test-py
